language: cpp

addons:
  apt:
    packages:
      - libsdl2-dev
      - libjpeg-turbo8-dev
      - zlib1g-dev
      - libpng12-dev

script:
  - ./tools/travis-build.sh "${host:-native}" "${flavour:-Release}" $opts

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
    - os: linux
      dist: trusty
      sudo: required
      compiler: clang

before_deploy:
  - export DEPLOY_FILE_NAME=kotf_$TRAVIS_OS_NAME-$CC.zip
  - echo "zipping into $DEPLOY_FILE_NAME"
  - cd $(pwd)/build/install
  - zip -r $DEPLOY_FILE_NAME . -i \*
  - echo "deploying $DEPLOY_FILE_NAME to GitHub"

deploy:
  provider: releases
  api_key: $GITHUB_KEY
  overwrite: true
  file: "$DEPLOY_FILE_NAME"
  skip_cleanup: true
  on:
    tags: true


#dist: trusty

#install:
#  - ./tools/travis-install.sh "${host:-native}" "${flavour:-Release}" $opts

#script:
#  - ./tools/travis-build.sh "${host:-native}" "${flavour:-Release}" $opts

#compiler: gcc
#env:
#  - ""
#  - flavour=Debug
#  - host=i686-linux-gnu
#  - host=i686-w64-mingw32
#  - host=x86_64-w64-mingw32

# One extra build with clang, its warnings are often better
#matrix:
#  include:
#    - compiler: clang
#      env: ""
